/*
WhyLabs Songbird

Testing FeatureWeightsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_FeatureWeightsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FeatureWeightsApiService GetColumnWeights", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var datasetId string

		resp, httpRes, err := apiClient.FeatureWeightsApi.GetColumnWeights(context.Background(), orgId, datasetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeatureWeightsApiService PutColumnWeights", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var datasetId string

		resp, httpRes, err := apiClient.FeatureWeightsApi.PutColumnWeights(context.Background(), orgId, datasetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
