/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEventsPathResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEventsPathResponse{}

// GetEventsPathResponse BatchGetEvents API response with a list of events
type GetEventsPathResponse struct {
	// A list of events
	Items []EventsPath `json:"items"`
}

// NewGetEventsPathResponse instantiates a new GetEventsPathResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEventsPathResponse(items []EventsPath) *GetEventsPathResponse {
	this := GetEventsPathResponse{}
	this.Items = items
	return &this
}

// NewGetEventsPathResponseWithDefaults instantiates a new GetEventsPathResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEventsPathResponseWithDefaults() *GetEventsPathResponse {
	this := GetEventsPathResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *GetEventsPathResponse) GetItems() []EventsPath {
	if o == nil {
		var ret []EventsPath
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *GetEventsPathResponse) GetItemsOk() ([]EventsPath, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *GetEventsPathResponse) SetItems(v []EventsPath) {
	o.Items = v
}

func (o GetEventsPathResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEventsPathResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableGetEventsPathResponse struct {
	value *GetEventsPathResponse
	isSet bool
}

func (v NullableGetEventsPathResponse) Get() *GetEventsPathResponse {
	return v.value
}

func (v *NullableGetEventsPathResponse) Set(val *GetEventsPathResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEventsPathResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEventsPathResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEventsPathResponse(val *GetEventsPathResponse) *NullableGetEventsPathResponse {
	return &NullableGetEventsPathResponse{value: val, isSet: true}
}

func (v NullableGetEventsPathResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEventsPathResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


