/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MissingRecentDataRequestConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MissingRecentDataRequestConfig{}

// MissingRecentDataRequestConfig struct for MissingRecentDataRequestConfig
type MissingRecentDataRequestConfig struct {
	Enable NullableBool `json:"enable,omitempty"`
}

// NewMissingRecentDataRequestConfig instantiates a new MissingRecentDataRequestConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMissingRecentDataRequestConfig() *MissingRecentDataRequestConfig {
	this := MissingRecentDataRequestConfig{}
	return &this
}

// NewMissingRecentDataRequestConfigWithDefaults instantiates a new MissingRecentDataRequestConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMissingRecentDataRequestConfigWithDefaults() *MissingRecentDataRequestConfig {
	this := MissingRecentDataRequestConfig{}
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MissingRecentDataRequestConfig) GetEnable() bool {
	if o == nil || isNil(o.Enable.Get()) {
		var ret bool
		return ret
	}
	return *o.Enable.Get()
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MissingRecentDataRequestConfig) GetEnableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enable.Get(), o.Enable.IsSet()
}

// HasEnable returns a boolean if a field has been set.
func (o *MissingRecentDataRequestConfig) HasEnable() bool {
	if o != nil && o.Enable.IsSet() {
		return true
	}

	return false
}

// SetEnable gets a reference to the given NullableBool and assigns it to the Enable field.
func (o *MissingRecentDataRequestConfig) SetEnable(v bool) {
	o.Enable.Set(&v)
}
// SetEnableNil sets the value for Enable to be an explicit nil
func (o *MissingRecentDataRequestConfig) SetEnableNil() {
	o.Enable.Set(nil)
}

// UnsetEnable ensures that no value is present for Enable, not even an explicit nil
func (o *MissingRecentDataRequestConfig) UnsetEnable() {
	o.Enable.Unset()
}

func (o MissingRecentDataRequestConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MissingRecentDataRequestConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Enable.IsSet() {
		toSerialize["enable"] = o.Enable.Get()
	}
	return toSerialize, nil
}

type NullableMissingRecentDataRequestConfig struct {
	value *MissingRecentDataRequestConfig
	isSet bool
}

func (v NullableMissingRecentDataRequestConfig) Get() *MissingRecentDataRequestConfig {
	return v.value
}

func (v *NullableMissingRecentDataRequestConfig) Set(val *MissingRecentDataRequestConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableMissingRecentDataRequestConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableMissingRecentDataRequestConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMissingRecentDataRequestConfig(val *MissingRecentDataRequestConfig) *NullableMissingRecentDataRequestConfig {
	return &NullableMissingRecentDataRequestConfig{value: val, isSet: true}
}

func (v NullableMissingRecentDataRequestConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMissingRecentDataRequestConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


