/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SetDefaultMembershipRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDefaultMembershipRequest{}

// SetDefaultMembershipRequest struct for SetDefaultMembershipRequest
type SetDefaultMembershipRequest struct {
	OrgId string `json:"orgId"`
	UserId string `json:"userId"`
}

// NewSetDefaultMembershipRequest instantiates a new SetDefaultMembershipRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDefaultMembershipRequest(orgId string, userId string) *SetDefaultMembershipRequest {
	this := SetDefaultMembershipRequest{}
	this.OrgId = orgId
	this.UserId = userId
	return &this
}

// NewSetDefaultMembershipRequestWithDefaults instantiates a new SetDefaultMembershipRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDefaultMembershipRequestWithDefaults() *SetDefaultMembershipRequest {
	this := SetDefaultMembershipRequest{}
	return &this
}

// GetOrgId returns the OrgId field value
func (o *SetDefaultMembershipRequest) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *SetDefaultMembershipRequest) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *SetDefaultMembershipRequest) SetOrgId(v string) {
	o.OrgId = v
}

// GetUserId returns the UserId field value
func (o *SetDefaultMembershipRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *SetDefaultMembershipRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *SetDefaultMembershipRequest) SetUserId(v string) {
	o.UserId = v
}

func (o SetDefaultMembershipRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDefaultMembershipRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orgId"] = o.OrgId
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

type NullableSetDefaultMembershipRequest struct {
	value *SetDefaultMembershipRequest
	isSet bool
}

func (v NullableSetDefaultMembershipRequest) Get() *SetDefaultMembershipRequest {
	return v.value
}

func (v *NullableSetDefaultMembershipRequest) Set(val *SetDefaultMembershipRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDefaultMembershipRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDefaultMembershipRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDefaultMembershipRequest(val *SetDefaultMembershipRequest) *NullableSetDefaultMembershipRequest {
	return &NullableSetDefaultMembershipRequest{value: val, isSet: true}
}

func (v NullableSetDefaultMembershipRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDefaultMembershipRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


