/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DistributionMonitorRequestConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributionMonitorRequestConfig{}

// DistributionMonitorRequestConfig struct for DistributionMonitorRequestConfig
type DistributionMonitorRequestConfig struct {
	Enable NullableBool `json:"enable,omitempty"`
	Threshold NullableFloat64 `json:"threshold,omitempty"`
}

// NewDistributionMonitorRequestConfig instantiates a new DistributionMonitorRequestConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributionMonitorRequestConfig() *DistributionMonitorRequestConfig {
	this := DistributionMonitorRequestConfig{}
	return &this
}

// NewDistributionMonitorRequestConfigWithDefaults instantiates a new DistributionMonitorRequestConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributionMonitorRequestConfigWithDefaults() *DistributionMonitorRequestConfig {
	this := DistributionMonitorRequestConfig{}
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DistributionMonitorRequestConfig) GetEnable() bool {
	if o == nil || isNil(o.Enable.Get()) {
		var ret bool
		return ret
	}
	return *o.Enable.Get()
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DistributionMonitorRequestConfig) GetEnableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enable.Get(), o.Enable.IsSet()
}

// HasEnable returns a boolean if a field has been set.
func (o *DistributionMonitorRequestConfig) HasEnable() bool {
	if o != nil && o.Enable.IsSet() {
		return true
	}

	return false
}

// SetEnable gets a reference to the given NullableBool and assigns it to the Enable field.
func (o *DistributionMonitorRequestConfig) SetEnable(v bool) {
	o.Enable.Set(&v)
}
// SetEnableNil sets the value for Enable to be an explicit nil
func (o *DistributionMonitorRequestConfig) SetEnableNil() {
	o.Enable.Set(nil)
}

// UnsetEnable ensures that no value is present for Enable, not even an explicit nil
func (o *DistributionMonitorRequestConfig) UnsetEnable() {
	o.Enable.Unset()
}

// GetThreshold returns the Threshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DistributionMonitorRequestConfig) GetThreshold() float64 {
	if o == nil || isNil(o.Threshold.Get()) {
		var ret float64
		return ret
	}
	return *o.Threshold.Get()
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DistributionMonitorRequestConfig) GetThresholdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Threshold.Get(), o.Threshold.IsSet()
}

// HasThreshold returns a boolean if a field has been set.
func (o *DistributionMonitorRequestConfig) HasThreshold() bool {
	if o != nil && o.Threshold.IsSet() {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given NullableFloat64 and assigns it to the Threshold field.
func (o *DistributionMonitorRequestConfig) SetThreshold(v float64) {
	o.Threshold.Set(&v)
}
// SetThresholdNil sets the value for Threshold to be an explicit nil
func (o *DistributionMonitorRequestConfig) SetThresholdNil() {
	o.Threshold.Set(nil)
}

// UnsetThreshold ensures that no value is present for Threshold, not even an explicit nil
func (o *DistributionMonitorRequestConfig) UnsetThreshold() {
	o.Threshold.Unset()
}

func (o DistributionMonitorRequestConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributionMonitorRequestConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Enable.IsSet() {
		toSerialize["enable"] = o.Enable.Get()
	}
	if o.Threshold.IsSet() {
		toSerialize["threshold"] = o.Threshold.Get()
	}
	return toSerialize, nil
}

type NullableDistributionMonitorRequestConfig struct {
	value *DistributionMonitorRequestConfig
	isSet bool
}

func (v NullableDistributionMonitorRequestConfig) Get() *DistributionMonitorRequestConfig {
	return v.value
}

func (v *NullableDistributionMonitorRequestConfig) Set(val *DistributionMonitorRequestConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributionMonitorRequestConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributionMonitorRequestConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributionMonitorRequestConfig(val *DistributionMonitorRequestConfig) *NullableDistributionMonitorRequestConfig {
	return &NullableDistributionMonitorRequestConfig{value: val, isSet: true}
}

func (v NullableDistributionMonitorRequestConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributionMonitorRequestConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


