/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PagerDutyNotificationAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagerDutyNotificationAction{}

// PagerDutyNotificationAction Pager Duty payload for Notification Actions
type PagerDutyNotificationAction struct {
	PagerDutyKey string `json:"pagerDutyKey"`
}

// NewPagerDutyNotificationAction instantiates a new PagerDutyNotificationAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagerDutyNotificationAction(pagerDutyKey string) *PagerDutyNotificationAction {
	this := PagerDutyNotificationAction{}
	this.PagerDutyKey = pagerDutyKey
	return &this
}

// NewPagerDutyNotificationActionWithDefaults instantiates a new PagerDutyNotificationAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagerDutyNotificationActionWithDefaults() *PagerDutyNotificationAction {
	this := PagerDutyNotificationAction{}
	return &this
}

// GetPagerDutyKey returns the PagerDutyKey field value
func (o *PagerDutyNotificationAction) GetPagerDutyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PagerDutyKey
}

// GetPagerDutyKeyOk returns a tuple with the PagerDutyKey field value
// and a boolean to check if the value has been set.
func (o *PagerDutyNotificationAction) GetPagerDutyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PagerDutyKey, true
}

// SetPagerDutyKey sets field value
func (o *PagerDutyNotificationAction) SetPagerDutyKey(v string) {
	o.PagerDutyKey = v
}

func (o PagerDutyNotificationAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagerDutyNotificationAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagerDutyKey"] = o.PagerDutyKey
	return toSerialize, nil
}

type NullablePagerDutyNotificationAction struct {
	value *PagerDutyNotificationAction
	isSet bool
}

func (v NullablePagerDutyNotificationAction) Get() *PagerDutyNotificationAction {
	return v.value
}

func (v *NullablePagerDutyNotificationAction) Set(val *PagerDutyNotificationAction) {
	v.value = val
	v.isSet = true
}

func (v NullablePagerDutyNotificationAction) IsSet() bool {
	return v.isSet
}

func (v *NullablePagerDutyNotificationAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagerDutyNotificationAction(val *PagerDutyNotificationAction) *NullablePagerDutyNotificationAction {
	return &NullablePagerDutyNotificationAction{value: val, isSet: true}
}

func (v NullablePagerDutyNotificationAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagerDutyNotificationAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


