/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProvisionDatabricksConnectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisionDatabricksConnectionResponse{}

// ProvisionDatabricksConnectionResponse struct for ProvisionDatabricksConnectionResponse
type ProvisionDatabricksConnectionResponse struct {
	WorkspaceId string `json:"workspaceId"`
	UserId string `json:"userId"`
	OrgId string `json:"orgId"`
}

// NewProvisionDatabricksConnectionResponse instantiates a new ProvisionDatabricksConnectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisionDatabricksConnectionResponse(workspaceId string, userId string, orgId string) *ProvisionDatabricksConnectionResponse {
	this := ProvisionDatabricksConnectionResponse{}
	this.WorkspaceId = workspaceId
	this.UserId = userId
	this.OrgId = orgId
	return &this
}

// NewProvisionDatabricksConnectionResponseWithDefaults instantiates a new ProvisionDatabricksConnectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisionDatabricksConnectionResponseWithDefaults() *ProvisionDatabricksConnectionResponse {
	this := ProvisionDatabricksConnectionResponse{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *ProvisionDatabricksConnectionResponse) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *ProvisionDatabricksConnectionResponse) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *ProvisionDatabricksConnectionResponse) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetUserId returns the UserId field value
func (o *ProvisionDatabricksConnectionResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ProvisionDatabricksConnectionResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ProvisionDatabricksConnectionResponse) SetUserId(v string) {
	o.UserId = v
}

// GetOrgId returns the OrgId field value
func (o *ProvisionDatabricksConnectionResponse) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ProvisionDatabricksConnectionResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ProvisionDatabricksConnectionResponse) SetOrgId(v string) {
	o.OrgId = v
}

func (o ProvisionDatabricksConnectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisionDatabricksConnectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspaceId"] = o.WorkspaceId
	toSerialize["userId"] = o.UserId
	toSerialize["orgId"] = o.OrgId
	return toSerialize, nil
}

type NullableProvisionDatabricksConnectionResponse struct {
	value *ProvisionDatabricksConnectionResponse
	isSet bool
}

func (v NullableProvisionDatabricksConnectionResponse) Get() *ProvisionDatabricksConnectionResponse {
	return v.value
}

func (v *NullableProvisionDatabricksConnectionResponse) Set(val *ProvisionDatabricksConnectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisionDatabricksConnectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisionDatabricksConnectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisionDatabricksConnectionResponse(val *ProvisionDatabricksConnectionResponse) *NullableProvisionDatabricksConnectionResponse {
	return &NullableProvisionDatabricksConnectionResponse{value: val, isSet: true}
}

func (v NullableProvisionDatabricksConnectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisionDatabricksConnectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


