/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProvisionNewUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisionNewUserResponse{}

// ProvisionNewUserResponse struct for ProvisionNewUserResponse
type ProvisionNewUserResponse struct {
	UserId string `json:"userId"`
	OrgId string `json:"orgId"`
	ModelId string `json:"modelId"`
}

// NewProvisionNewUserResponse instantiates a new ProvisionNewUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisionNewUserResponse(userId string, orgId string, modelId string) *ProvisionNewUserResponse {
	this := ProvisionNewUserResponse{}
	this.UserId = userId
	this.OrgId = orgId
	this.ModelId = modelId
	return &this
}

// NewProvisionNewUserResponseWithDefaults instantiates a new ProvisionNewUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisionNewUserResponseWithDefaults() *ProvisionNewUserResponse {
	this := ProvisionNewUserResponse{}
	return &this
}

// GetUserId returns the UserId field value
func (o *ProvisionNewUserResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ProvisionNewUserResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ProvisionNewUserResponse) SetUserId(v string) {
	o.UserId = v
}

// GetOrgId returns the OrgId field value
func (o *ProvisionNewUserResponse) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ProvisionNewUserResponse) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ProvisionNewUserResponse) SetOrgId(v string) {
	o.OrgId = v
}

// GetModelId returns the ModelId field value
func (o *ProvisionNewUserResponse) GetModelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value
// and a boolean to check if the value has been set.
func (o *ProvisionNewUserResponse) GetModelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelId, true
}

// SetModelId sets field value
func (o *ProvisionNewUserResponse) SetModelId(v string) {
	o.ModelId = v
}

func (o ProvisionNewUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisionNewUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["orgId"] = o.OrgId
	toSerialize["modelId"] = o.ModelId
	return toSerialize, nil
}

type NullableProvisionNewUserResponse struct {
	value *ProvisionNewUserResponse
	isSet bool
}

func (v NullableProvisionNewUserResponse) Get() *ProvisionNewUserResponse {
	return v.value
}

func (v *NullableProvisionNewUserResponse) Set(val *ProvisionNewUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisionNewUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisionNewUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisionNewUserResponse(val *ProvisionNewUserResponse) *NullableProvisionNewUserResponse {
	return &NullableProvisionNewUserResponse{value: val, isSet: true}
}

func (v NullableProvisionNewUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisionNewUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


