/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RefreshConnectionByOrgIdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshConnectionByOrgIdResponse{}

// RefreshConnectionByOrgIdResponse struct for RefreshConnectionByOrgIdResponse
type RefreshConnectionByOrgIdResponse struct {
	Connection DatabricksConnection `json:"connection"`
}

// NewRefreshConnectionByOrgIdResponse instantiates a new RefreshConnectionByOrgIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshConnectionByOrgIdResponse(connection DatabricksConnection) *RefreshConnectionByOrgIdResponse {
	this := RefreshConnectionByOrgIdResponse{}
	this.Connection = connection
	return &this
}

// NewRefreshConnectionByOrgIdResponseWithDefaults instantiates a new RefreshConnectionByOrgIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshConnectionByOrgIdResponseWithDefaults() *RefreshConnectionByOrgIdResponse {
	this := RefreshConnectionByOrgIdResponse{}
	return &this
}

// GetConnection returns the Connection field value
func (o *RefreshConnectionByOrgIdResponse) GetConnection() DatabricksConnection {
	if o == nil {
		var ret DatabricksConnection
		return ret
	}

	return o.Connection
}

// GetConnectionOk returns a tuple with the Connection field value
// and a boolean to check if the value has been set.
func (o *RefreshConnectionByOrgIdResponse) GetConnectionOk() (*DatabricksConnection, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connection, true
}

// SetConnection sets field value
func (o *RefreshConnectionByOrgIdResponse) SetConnection(v DatabricksConnection) {
	o.Connection = v
}

func (o RefreshConnectionByOrgIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshConnectionByOrgIdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connection"] = o.Connection
	return toSerialize, nil
}

type NullableRefreshConnectionByOrgIdResponse struct {
	value *RefreshConnectionByOrgIdResponse
	isSet bool
}

func (v NullableRefreshConnectionByOrgIdResponse) Get() *RefreshConnectionByOrgIdResponse {
	return v.value
}

func (v *NullableRefreshConnectionByOrgIdResponse) Set(val *RefreshConnectionByOrgIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshConnectionByOrgIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshConnectionByOrgIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshConnectionByOrgIdResponse(val *RefreshConnectionByOrgIdResponse) *NullableRefreshConnectionByOrgIdResponse {
	return &NullableRefreshConnectionByOrgIdResponse{value: val, isSet: true}
}

func (v NullableRefreshConnectionByOrgIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshConnectionByOrgIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


