/*
WhyLabs Songbird

WhyLabs API that enables end-to-end AI observability

API version: 0.1
Contact: support@whylabs.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RunJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunJobRequest{}

// RunJobRequest struct for RunJobRequest
type RunJobRequest struct {
	// Look up a connection by the org that is connected to.
	OrgId NullableString `json:"orgId,omitempty"`
	// Look up a connection by the workspace that it originates from.
	WorkspaceId NullableString `json:"workspaceId,omitempty"`
	// The id of the job to run in the connected Databricks workspace.
	JobId int64 `json:"jobId"`
}

// NewRunJobRequest instantiates a new RunJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunJobRequest(jobId int64) *RunJobRequest {
	this := RunJobRequest{}
	this.JobId = jobId
	return &this
}

// NewRunJobRequestWithDefaults instantiates a new RunJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunJobRequestWithDefaults() *RunJobRequest {
	this := RunJobRequest{}
	return &this
}

// GetOrgId returns the OrgId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunJobRequest) GetOrgId() string {
	if o == nil || isNil(o.OrgId.Get()) {
		var ret string
		return ret
	}
	return *o.OrgId.Get()
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunJobRequest) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgId.Get(), o.OrgId.IsSet()
}

// HasOrgId returns a boolean if a field has been set.
func (o *RunJobRequest) HasOrgId() bool {
	if o != nil && o.OrgId.IsSet() {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given NullableString and assigns it to the OrgId field.
func (o *RunJobRequest) SetOrgId(v string) {
	o.OrgId.Set(&v)
}
// SetOrgIdNil sets the value for OrgId to be an explicit nil
func (o *RunJobRequest) SetOrgIdNil() {
	o.OrgId.Set(nil)
}

// UnsetOrgId ensures that no value is present for OrgId, not even an explicit nil
func (o *RunJobRequest) UnsetOrgId() {
	o.OrgId.Unset()
}

// GetWorkspaceId returns the WorkspaceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RunJobRequest) GetWorkspaceId() string {
	if o == nil || isNil(o.WorkspaceId.Get()) {
		var ret string
		return ret
	}
	return *o.WorkspaceId.Get()
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RunJobRequest) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkspaceId.Get(), o.WorkspaceId.IsSet()
}

// HasWorkspaceId returns a boolean if a field has been set.
func (o *RunJobRequest) HasWorkspaceId() bool {
	if o != nil && o.WorkspaceId.IsSet() {
		return true
	}

	return false
}

// SetWorkspaceId gets a reference to the given NullableString and assigns it to the WorkspaceId field.
func (o *RunJobRequest) SetWorkspaceId(v string) {
	o.WorkspaceId.Set(&v)
}
// SetWorkspaceIdNil sets the value for WorkspaceId to be an explicit nil
func (o *RunJobRequest) SetWorkspaceIdNil() {
	o.WorkspaceId.Set(nil)
}

// UnsetWorkspaceId ensures that no value is present for WorkspaceId, not even an explicit nil
func (o *RunJobRequest) UnsetWorkspaceId() {
	o.WorkspaceId.Unset()
}

// GetJobId returns the JobId field value
func (o *RunJobRequest) GetJobId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *RunJobRequest) GetJobIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *RunJobRequest) SetJobId(v int64) {
	o.JobId = v
}

func (o RunJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OrgId.IsSet() {
		toSerialize["orgId"] = o.OrgId.Get()
	}
	if o.WorkspaceId.IsSet() {
		toSerialize["workspaceId"] = o.WorkspaceId.Get()
	}
	toSerialize["jobId"] = o.JobId
	return toSerialize, nil
}

type NullableRunJobRequest struct {
	value *RunJobRequest
	isSet bool
}

func (v NullableRunJobRequest) Get() *RunJobRequest {
	return v.value
}

func (v *NullableRunJobRequest) Set(val *RunJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRunJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRunJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunJobRequest(val *RunJobRequest) *NullableRunJobRequest {
	return &NullableRunJobRequest{value: val, isSet: true}
}

func (v NullableRunJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


